### ISSUE TITLE
No passwd on root user.

### ISSUE THREAD

**Issue by kubast2** [agowa338/WSL-DistroLauncher-Alpine#14]
I had to use "mkpasswd --method=md5" to generate a hash and then put it into shadow files from windows. The installer should ask for at least root password change on the first install, since you guys don't use sudo.

**Comment by kubast2** [comment]
I have already worked around it btw.

**Comment by agowa338** [comment]
I'll fix that in the next release.
You know that you could also run `wsl.exe --user root --distribution Alpine`.

P.S. that also works from within wsl, therefore the sudo/su and password stuff is quite pointless anyway...

**Comment by Jochnickel** [comment]
theoretically, if you just use `wsl -e ...` , it wont execute windows `.exe`-files. So maybe 99.9% pointless :P

**Comment by Jochnickel** [comment]
but nvm
`shell
C:\Users\JJ>wsl -e ash -c "wsl.exe -u root ls /root/"
fileInRoot`

**Comment by agowa338** [comment]
From the help page:
```    If no command line is provided, wsl.exe launches the default shell.

    --exec, -e <CommandLine>
        Execute the specified command without using the default Linux shell.
```
and because it doesn't launch the default shell, you'll maybe just be missing the PATH environment variable...
And without it, wsl just doesn't find the windows executable, but full path e.g. `/mnt/c/Windows/...` would still work...
That's also why your 2nd example did work. Because you're invoking ash yourself.

e.g. `wsl.exe -e calc.exe` doesn't work, but `wsl.exe -e /mnt/c/Windows/System32/calc.exe` does.

One could however change the mount behavior using [/etc/wsl.conf](https://docs.microsoft.com/de-de/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf), but I'm unsure if that is already available in all supported windows 10 versions (especially education and enterprise)
