### ISSUE TITLE
Free trial status in Microsoft Store

### ISSUE THREAD

**Issue by rufanov** [agowa338/WSL-DistroLauncher-Alpine#32]
Why this wsl launcher currently published as app with trial period?

![alpine-wsl-free-trial](https://user-images.githubusercontent.com/502813/104741399-df6a6400-5794-11eb-9721-1f6d6474c65b.png)

It's seems little weird for fork of opensource project... Or it's planned to convert this launcher to be paid product in the future?

**Comment by rufanov** [comment]
Also current app logo in Microsoft Store is very non-contrast, almost to unreadable level.. Maybe different background/foreground colors should be used?

**Comment by agowa338** [comment]
> Also current app logo in Microsoft Store is very non-contrast, almost to unreadable level.. Maybe different background/foreground colors should be used?
The icon looks strange because for some reason the transparency isn't working in windows store. I had contact with support and I was told back than with the initial release that this is a bug on there side and that they're working on a fix...
Also the color is the official color, the only issue is the bugged transparence, this is how it looks like in the dev center:
![image](https://user-images.githubusercontent.com/2544867/104791771-36276c00-579c-11eb-8834-cfd9cd3a16a9.png)


>Why this wsl launcher currently published as app with trial period?
Because I initially selected it and now that setting is read only (and when publishing an updated version I always forgot to change it)
![image](https://user-images.githubusercontent.com/2544867/104791654-c44f2280-579b-11eb-80a1-717beb7c7569.png)

**Comment by rufanov** [comment]
Thank you for such a detailed answer!

**Comment by jirutka** [comment]
Have you tried to drop transparency and use white background?

**Comment by agowa338** [comment]
@jirutka I'll look into it with the next "release". That should work, but currently I don't know which one is displayed in the store and which one in the start menu, will have to test that before. I was hoping that they would fix that and than forgot about it.
