### ISSUE TITLE
default-user not working

### ISSUE THREAD

**Issue by apendragon** [agowa338/WSL-DistroLauncher-Alpine#4]
Hi,

Thank you for your work.
On my side I can't change the default-user.
User has first been created in the WSL and I can switch from root to him by using "`su - bob`" for example.

If I set the default user as described in the command usage:
`alpine config --default-user bob`

There is no stdout/stderr.

When I relaunch Alpine I'm still root.

**Windows version:**
`systeminfo | Select-String "^OS Name","^OS Version"

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
`
**Alpine version :** latest available from the windows store

Thanks for your help

**Comment by agowa338** [comment]
The issue is most likely within the wsl api former windows 10 versions had the same issue and enterprise is a bit behind regarding feature additions if I correctly remember.

There is no really much, that I could do except including the Userland binaries by itself.

If it is not a production system, but only a dev box, you could just copy over these files from a newer windows 10 build:
C:/Windows/System32/wslapi.dll
and maybe also:
C:/Windows/System32/wsl.exe
C:/Windows/System32/wslconfig.exe
C:/Windows/System32/lxss
